# Generated by Django 5.0.6 on 2024-06-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('usn', models.CharField(max_length=122)),
                ('sem', models.CharField(max_length=122)),
            ],
        ),
    ]
